on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/15 * * * *'
  push:
    branches:
      - main
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2

    - name: User Node.js 12
      uses: actions/setup-node@v1
      with:
        version: 12

    - name: yarn install, yarn build, yarn start
      env: 
        VISTA_ENDPOINT: ${{ secrets.VISTA_ENDPOINT }}
        VISTA_KEY: ${{ secrets.VISTA_KEY }}
      run: |
        yarn install
        yarn build
        yarn start

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./data/
        git-ftp-args: --all